image: python:latest

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - pip install flake8 pytest pytest-mock
    - flake8 --exclude venv --ignore=W605 --max-line-length 125 ..
    - python -m pytest -n=4 --dist=loadfile -rN --tb=line -v -k tests

