image: continuumio/miniconda3:latest

before_script:
  - conda env create -f requirements.yml
  - source activate koopa

test:
  script:
    - pip install flake8 pytest pytest-mock
    - flake8 --exclude venv --ignore=W605,E731,E131,F821 --max-line-length 150 ..
    - pytest tests


