image: python:3.8.17-slim-bullseye

before_script:
  - python setup.py install

test:
  script:
    - pip install flake8 pytest pytest-mock
    - flake8 --exclude venv --ignore=W605,E731,E131,F821 --max-line-length 150 ..
    - pytest tests


