image: python:latest

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python install setup.py

test:
  script:
    - pip install flake8 pytest pytest-mock
    - flake8 --exclude venv --ignore=W605,F821 --max-line-length 125 ..
    - pytest tests

